# Generated by Django 4.2.6 on 2023-10-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_book'),
    ]

    operations = [
    ]
